# Generated by Django 4.2.2 on 2024-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0016_teams_completed_task_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
