# Generated by Django 4.2.2 on 2025-07-01 06:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_panels_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_short_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
