# Generated by Django 4.2.2 on 2025-07-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0018_alter_teams_team_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['-is_active', '-team_of', 'team_name'], 'verbose_name': 'Registered Team'},
        ),
    ]
