# Generated by Django 4.2.2 on 2026-04-23 11:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0019_alter_teams_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/societies_and_ag/background_image/', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='mission_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/societies_and_ag/mission_picture/', verbose_name='Mission Image'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='vision_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/societies_and_ag/vision_picture/', verbose_name='Vision Image'),
        ),
    ]
