# Generated by Django 4.2.2 on 2025-07-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0004_alter_renewal_form_info_bkash_payment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal_requests',
            name='ieee_account_password',
            field=models.CharField(db_column='ieee_account_password', max_length=500),
        ),
        migrations.RenameField(
            model_name='renewal_requests',
            old_name='ieee_account_password',
            new_name='_ieee_account_password',
        ),
    ]
