# Generated by Django 4.2.2 on 2025-11-17 20:30

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0019_alter_teams_options'),
        ('membership_development_team', '0005_alter_renewal_requests_ieee_account_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal_requests',
            name='payment_type',
            field=models.CharField(choices=[('mdt', 'MDT'), ('self', 'Self'), ('not_set', 'Not Set')], default='not_set', max_length=9),
        ),
        migrations.AddField(
            model_name='renewal_requests',
            name='renewal_screenshot',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='MDT/Renewal_Screenshots/'),
        ),
        migrations.AddField(
            model_name='renewal_requests',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.teams'),
        ),
    ]
