# Generated by Django 4.2.2 on 2025-06-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('total_attendee', models.IntegerField()),
                ('ieee_attendee', models.IntegerField(blank=True, null=True)),
                ('non_ieee_attendee', models.IntegerField(blank=True, null=True)),
                ('agendas', models.JSONField(default=list)),
                ('discussion', models.TextField()),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('co_host', models.CharField(blank=True, max_length=255, null=True)),
                ('guest', models.CharField(blank=True, max_length=255, null=True)),
                ('written_by', models.CharField(max_length=255)),
            ],
        ),
    ]
