# Generated by Django 4.2.2 on 2025-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_minutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutes',
            name='agendas',
            field=models.JSONField(default=list),
        ),
    ]
