# Generated by Django 4.2.2 on 2025-06-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_minutes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingminutes',
            old_name='date',
            new_name='meeting_date',
        ),
    ]
