# Generated by Django 4.2.2 on 2025-06-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_panels_display'),
        ('meeting_minutes', '0002_rename_date_meetingminutes_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='sc_ag',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.teams'),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='discussion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='ieee_attendee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='non_ieee_attendee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='total_attendee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='written_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
