# Generated by Django 4.2.2 on 2025-07-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_members_department_members_school'),
        ('meeting_minutes', '0003_meetingminutes_sc_ag_meetingminutes_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinutesAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('ViewOnly', 'ViewOnly'), ('Edit', 'Edit'), ('Restricted', 'Restricted')], default='Restricted', max_length=20)),
                ('meeting_minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_minutes.meetingminutes')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
            ],
            options={
                'verbose_name': 'Meeting Minutes Access',
            },
        ),
    ]
