# Generated by Django 4.2.2 on 2025-07-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0003_homepagethought'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagethought',
            old_name='quote',
            new_name='thoughts',
        ),
    ]
