# Generated by Django 4.2.2 on 2025-07-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0004_rename_quote_homepagethought_thoughts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagethought',
            old_name='thoughts',
            new_name='quote',
        ),
    ]
