# Generated by Django 4.2.2 on 2025-07-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0005_rename_thoughts_homepagethought_quote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageThought',
            new_name='HomePage_Thoughts',
        ),
    ]
