# Generated by Django 4.2.2 on 2025-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0006_rename_homepagethought_homepage_thoughts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPictureWithStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/ribbon_picture/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
            ],
        ),
    ]
