# Generated by Django 4.2.2 on 2025-07-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0007_bannerpicturewithstat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerPictureWithStat',
        ),
        migrations.DeleteModel(
            name='HomePage_Thoughts',
        ),
    ]
