# Generated by Django 4.2.2 on 2025-07-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0009_homepage_thoughts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage_Thoughts',
        ),
    ]
