# Generated by Django 4.2.2 on 2025-06-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_nsu_majors'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment_session',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitment_session',
            name='session_end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
