# Generated by Django 4.2.2 on 2025-06-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_recruitment_session_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment_session',
            name='recruitment_event_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
