# Generated by Django 4.2.2 on 2025-02-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_panels_display'),
        ('task_assignation', '0030_member_task_point_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_panel_of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='port.panels'),
            preserve_default=False,
        ),
    ]
