# Generated by Django 4.2.2 on 2025-02-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_members_department_members_school'),
        ('port', '0017_panels_display'),
        ('task_assignation', '0031_task_task_panel_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Task_Points_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('panel_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.panels')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.teams')),
            ],
            options={
                'verbose_name': 'Team Task Points History',
            },
        ),
        migrations.CreateModel(
            name='Member_Task_Points_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
                ('panel_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.panels')),
            ],
            options={
                'verbose_name': 'Member Task Points History',
            },
        ),
    ]
