# Generated by Django 4.2.2 on 2025-04-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0032_team_task_points_history_member_task_points_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_category',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
