# Generated by Django 4.2.2 on 2025-07-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0018_alter_teams_team_short_description'),
        ('task_assignation', '0033_task_category_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_category',
            name='team',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.SET_DEFAULT, to='port.teams'),
        ),
    ]
