# Generated by Django 4.2.2 on 2025-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0022_events_selected_attendee_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_feedback',
            name='satisfaction',
            field=models.CharField(choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('not_satisfied', 'Not Satisfied')], max_length=50),
        ),
    ]
