# Generated by Django 4.2.2 on 2026-01-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0023_alter_event_feedback_satisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_feedback',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
