
from django.urls import path
from .views import *


app_name='main_website.api'

urlpatterns = [
    path('get_hero_section_landing/', HeroSectionLandingView.as_view(), name='hero_section_landing'),
    path('get_achievements/', AchievementListView.as_view(), name='achievements_list'),
    path('get_achievements/<int:sc_ag_primary>/', AchievementListView.as_view(), name='achievements_list_sc_ag'),
    path('get_achievements/landing/', AchievementListLandingView.as_view(), name='achievements_list_landing'),
    path('get_achievements/landing/<int:sc_ag_primary>/', AchievementListLandingView.as_view(), name='achievements_list_landing_sc_ag'),
    path('get_sc_ag_stats/', ScAgStats.as_view(), name='sc_ag_stats'),
    path('get_events_stats/', EventsStats.as_view(), name='events_stats'),
    path('get_blogs/landing/', BlogsListLandingView.as_view(), name='blogs_list_landing'),
    path('get_blogs/', BlogsView.as_view(), name='blogs_list'),
    path('get_blog_details/<int:blog_id>/', BlogView.as_view(), name='blog_view'),
    path('get_volunteer_awards/', VolunteerAwardsListView.as_view(), name='volunteer_awards_list'),
    path('get_toolkit/', ToolkitListView.as_view(), name='toolkit_list'),
    path('get_mega_featured_events/<int:sc_ag_primary>/', MegaEvents_FeaturedEventsListView.as_view(), name='mega_featured_events_list'),
    path('get_sb_news/', SBNewsListView.as_view(), name='sb_news_list'),
    path('get_online_news/', OnlineNewsListView.as_view(), name='online_news_list'),
    path('get_research_papers/', ResearchPapersListView.as_view(), name='research_papers_list'),
    path('get_all_members/', AllMembersListView.as_view(), name='all_members_list'),
    path('get_all_members_stats/', AllMembersStats.as_view(), name='all_members_stats'),
    path('get_sc_ag_details/<int:sc_ag_primary>/', SCAGDetails.as_view(), name='sc_ag_details'),
    path('get_panels/', PanelsListView.as_view(), name='panels_list'),
    path('get_panels/<int:sc_ag_primary>/', PanelsListView.as_view(), name='panels_list_sc_ag'),
    path('get_panel_executives/', PanelExecutives.as_view(), name='panel_executives'),
    path('get_sc_ag_panel_executives/<int:sc_ag_primary>/', SCAGPanelExecutives.as_view(), name='sc_ag_panel_executives'),
    path('get_sc_ag_panel_executives/<int:sc_ag_primary>/<str:panel_year>/', SCAGPanelExecutives.as_view(), name='sc_ag_panel_executives_year'),
    path('get_panel_executives/<str:panel_year>/', PanelExecutives.as_view(), name='panel_executives_sc_ag'),
    path('get_event_details/<int:event_id>/', EventView.as_view(), name='event_view'),
    path('get_mega_event_details/<int:event_id>/', MegaEventView.as_view(), name='mega_event_view'),
    path('get_contact_info/', ContactInfoView.as_view(), name='contact_info'),
    path('get_ieee_r10_details/', IEEERegion10Details.as_view(), name='ieee_r10_details'),
    path('get_all_events/', EventsListView.as_view(), name='events_list'),
    path('get_upcoming_event/', UpcomingEvent.as_view(), name='upcoming_event'),
    path('get_team_details/<int:team_primary>/', TeamInfoView.as_view(), name='team_info'),
    path('get_teams/', TeamsListView.as_view(), name='teams_list'),
    path('get_officers/', OfficersListView.as_view(), name='officers_list'),
    path('get_officers/<int:team_primary>/', OfficersListView.as_view(), name='team_officers_list'),
    path('get_volunteers/', VolunteersListView.as_view(), name='volunteers_list'),
    path('get_volunteers/<int:team_primary>/', VolunteersListView.as_view(), name='team_volunteers_list'),
    path('get_sb_news_details/<int:news_id>/', SBNewsDetails.as_view(), name='sb_news_details'),
    path('get_member_details/<int:ieee_id>/', MemberProfileView.as_view(), name='member_profile'),
    path('get_exemplary_members/', ExemplaryMembersListView.as_view(), name='exemplary_members_list'),
    path('get_faq/', FAQView.as_view(), name='faq_details'),
    path('get_gallery/', GalleryView.as_view(), name='gallery_view'),
    path('sc_ag_feedback/', SC_AG_FeedBack.as_view(), name='branch_feedback'),
    path('sc_ag_feedback/<int:sc_ag_primary>/', SC_AG_FeedBack.as_view(), name='sc_ag_feedback'),
    path('add_research_paper/', AddResearchPaperView.as_view(), name='add_research_paper'),
    path('api/switches/', SwitchesAPI.as_view()),
    path('event_feedback/<int:event_id>/', EventFeedbackView.as_view(), name='event_feedback'),
    path('get_event_feedbacks/<int:event_id>/', EventFeedbackView.as_view(), name='event_feedback_list'),
    path('get_portal_developers/', PortalDevelopersList.as_view(), name='portal_developers_list'),
]
