# Generated by Django 4.2.2 on 2026-02-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0024_event_feedback_approved'),
        ('graphics_team', '0005_alter_graphics_drive_links_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_types', to='central_events.events')),
            ],
            options={
                'verbose_name': 'Certificate Type',
            },
        ),
        migrations.CreateModel(
            name='Certificate_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_template', models.FileField(blank=True, null=True, upload_to='certificates/svg/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graphics_team.certificate')),
            ],
            options={
                'verbose_name': 'Certificate Template',
            },
        ),
        migrations.CreateModel(
            name='Certificate_Receivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('email', models.CharField(max_length=40)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics_team.certificate')),
            ],
            options={
                'verbose_name': 'Certificate Receivers',
            },
        ),
    ]
