# Generated by Django 4.2.2 on 2026-02-15 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graphics_team', '0006_certificate_certificate_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Receiver_Download_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('otp_code', models.CharField(max_length=128)),
                ('otp_expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics_team.certificate')),
                ('certificate_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics_team.certificate_receivers')),
            ],
            options={
                'verbose_name': 'Certificate Receiver Download Request',
            },
        ),
        migrations.CreateModel(
            name='Certificate_Receiver_Download_URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('download_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graphics_team.certificate_receiver_download_request')),
            ],
            options={
                'verbose_name': 'Certificate Public Download URL',
            },
        ),
        migrations.CreateModel(
            name='Certificate_Public_URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graphics_team.certificate')),
            ],
            options={
                'verbose_name': 'Certificate Public URL',
            },
        ),
    ]
