# Generated by Django 4.2.2 on 2026-02-24 23:37

from django.db import migrations, models
import system_administration.models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics_team', '0007_certificate_receiver_download_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_template',
            name='svg_template',
            field=models.FileField(blank=True, null=True, storage=system_administration.models.PrivateFileStorage(), upload_to='certificates/svg/'),
        ),
    ]
