# Generated by Django 4.2.2 on 2025-03-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0013_branch_data_access_manage_email_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='fct_data_access',
            name='create_budget_access',
            field=models.BooleanField(default=False, verbose_name='Create Budget Access'),
        ),
        migrations.AlterField(
            model_name='fct_data_access',
            name='manage_team_access',
            field=models.BooleanField(default=False, verbose_name='Manage Team Permission'),
        ),
    ]
