# Generated by Django 4.2.2 on 2025-10-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0014_fct_data_access_create_budget_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_log',
            name='object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
