# Generated by Django 4.2.2 on 2026-02-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0015_alter_general_log_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics_data_access',
            name='certificates_access',
            field=models.BooleanField(default=False, verbose_name='Certificates Access'),
        ),
        migrations.AddField(
            model_name='graphics_data_access',
            name='certificates_view_access',
            field=models.BooleanField(default=False, verbose_name='Certificates View Access'),
        ),
    ]
