# Generated by Django 4.2.2 on 2025-04-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0015_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
