# Generated by Django 4.2.2 on 2025-05-24 12:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('port', '0017_panels_display'),
        ('central_events', '0022_events_selected_attendee_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('entry_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_type', models.CharField(choices=[('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out'), ('NOT_SET', 'NOT SET')], default='NOT_SET', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('contact', models.CharField(blank=True, max_length=40, null=True)),
                ('remarks', models.TextField()),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BKASH', 'Bkash'), ('NAGAD', 'Nagad')], default='CASH', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Wallet Entry',
            },
        ),
        migrations.CreateModel(
            name='WalletEntryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('background_colour', models.CharField(default='#FF9500', max_length=9)),
                ('text_colour', models.CharField(default='#FF9500', max_length=9)),
            ],
            options={
                'verbose_name': 'Wallet Entry Category',
            },
        ),
        migrations.CreateModel(
            name='WalletEventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=12)),
                ('wallet_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_events.events')),
            ],
            options={
                'verbose_name': 'Wallet Event Status',
            },
        ),
        migrations.CreateModel(
            name='WalletEntryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='Wallet/Wallet_Documents/')),
                ('wallet_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.walletentry')),
            ],
            options={
                'verbose_name': 'Wallet Entry File',
            },
        ),
        migrations.AddField(
            model_name='walletentry',
            name='categories',
            field=models.ManyToManyField(related_name='wallet_entries', to='wallet.walletentrycategory'),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='entry_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central_events.events'),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='sc_ag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='port.chapters_society_and_affinity_groups'),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='port.panels'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sc_ag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'Wallet',
            },
        ),
    ]
