# Generated by Django 4.2.2 on 2025-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_walletentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletentrycategory',
            name='background_colour',
            field=models.CharField(default='#FF9500', max_length=9),
        ),
        migrations.AddField(
            model_name='walletentrycategory',
            name='text_colour',
            field=models.CharField(default='#FF9500', max_length=9),
        ),
        migrations.AlterField(
            model_name='walletentry',
            name='entry_type',
            field=models.CharField(choices=[('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out'), ('NOT_SET', 'NOT SET')], default='NOT_SET'),
        ),
    ]
