# Generated by Django 4.2.2 on 2025-05-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_walletentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletentrycategory',
            name='colour',
            field=models.CharField(default='#FF9500'),
        ),
    ]
