# Generated by Django 4.2.2 on 2025-05-20 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0022_events_selected_attendee_list'),
        ('wallet', '0003_walletentrycategory_background_colour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletentry',
            name='status',
        ),
        migrations.CreateModel(
            name='WalletEventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='ONGOING')),
                ('wallet_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_events.events')),
            ],
            options={
                'verbose_name': 'Wallet Event Status',
            },
        ),
    ]
