# Generated by Django 4.2.2 on 2025-05-19 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_walletentrycategory_background_colour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletentry',
            name='status',
        ),
        migrations.CreateModel(
            name='WalletEntryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='ONGOING')),
                ('wallet_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.walletentry')),
            ],
            options={
                'verbose_name': 'Wallet Entry Status',
            },
        ),
    ]
