# Generated by Django 4.2.2 on 2025-05-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_walletentrycategory_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletentry',
            name='entry_type',
            field=models.CharField(choices=[('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out'), ('NOT_SET', 'NOT SET')], default='NOT_SET'),
        ),
    ]
