# Generated by Django 4.2.2 on 2025-05-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_walletentry_status_walleteventstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
