# Generated by Django 4.2.2 on 2025-03-28 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('port', '0017_panels_display'),
        ('users', '0033_members_department_members_school'),
        ('central_events', '0022_events_selected_attendee_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Budget Sheet', max_length=150)),
                ('costBreakdownData', models.JSONField(default=dict)),
                ('revenueBreakdownData', models.JSONField(default=dict)),
                ('total_cost', models.FloatField(default=0.0)),
                ('total_revenue', models.FloatField(default=0.0)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central_events.events')),
                ('sheet_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'Budget Sheet',
            },
        ),
        migrations.CreateModel(
            name='BudgetSheetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('ViewOnly', 'ViewOnly'), ('Edit', 'Edit'), ('Restricted', 'Restricted')], default='Restricted', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_and_corporate_team.budgetsheet')),
            ],
            options={
                'verbose_name': 'Budget Sheet Access',
            },
        ),
    ]
