# Generated by Django 4.2.2 on 2025-04-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_panels_display'),
        ('finance_and_corporate_team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSheetSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_signature', models.TextField()),
                ('right_signature', models.TextField()),
                ('sc_ag_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'Budget Sheet Signature',
            },
        ),
    ]
