# Generated by Django 4.2.2 on 2025-04-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_and_corporate_team', '0002_budgetsheetsignature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetsheetsignature',
            old_name='sc_ag_primary',
            new_name='sc_ag',
        ),
    ]
