# Generated by Django 4.2.2 on 2025-04-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_and_corporate_team', '0003_rename_sc_ag_primary_budgetsheetsignature_sc_ag'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsheet',
            name='usd_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
