# Generated by Django 4.2.2 on 2025-04-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_and_corporate_team', '0004_budgetsheet_usd_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsheet',
            name='show_usd_rates',
            field=models.BooleanField(default=False),
        ),
    ]
