# Generated by Django 4.2.2 on 2025-01-10 11:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0009_delete_volunteerofthemonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='award_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=25000, null=True),
        ),
    ]
