# Generated by Django 4.2.2 on 2025-06-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0010_alter_achievements_award_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('nsu_ieee_email', models.CharField(blank=True, max_length=80, null=True)),
                ('chair_email', models.CharField(blank=True, max_length=80, null=True)),
                ('membership_queries_number', models.CharField(blank=True, max_length=80, null=True)),
                ('corporate_engagement_number', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
            },
        ),
    ]
