# Generated by Django 4.2.2 on 2025-07-23 19:29

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0011_contact_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagetopbanner',
            options={'verbose_name': 'Homepage Banner Picture or video With Texts'},
        ),
        migrations.AddField(
            model_name='homepagetopbanner',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/homepage/ribbon_picture'),
        ),
        migrations.AddField(
            model_name='homepagetopbanner',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagetopbanner',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
