# Generated by Django 4.2.2 on 2025-07-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0012_alter_homepagetopbanner_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagetopbanner',
            old_name='youtube_url',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='homepagetopbanner',
            name='image',
        ),
    ]
