# Generated by Django 4.2.2 on 2025-07-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0013_rename_youtube_url_homepagetopbanner_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
            ],
        ),
    ]
