# Generated by Django 4.2.2 on 2025-08-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0014_mediatoggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagetopbanner',
            name='video_caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
