# Generated by Django 4.2.2 on 2025-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0015_homepagetopbanner_video_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagetopbanner',
            name='video_caption',
        ),
        migrations.AlterField(
            model_name='homepagetopbanner',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepagetopbanner',
            name='button_url',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagetopbanner',
            name='first_layer_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepagetopbanner',
            name='first_layer_text_colored',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepagetopbanner',
            name='third_layer_text',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
