# Generated by Django 4.2.2 on 2025-09-16 19:36

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0016_remove_homepagetopbanner_video_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagetopbanner',
            name='video_url',
        ),
        migrations.AddField(
            model_name='homepagetopbanner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='main_website_files/homepage/landing_video'),
        ),
        migrations.AlterField(
            model_name='homepagetopbanner',
            name='banner_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/homepage/banner_pictures'),
        ),
    ]
