# Generated by Django 4.2.2 on 2025-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0017_remove_homepagetopbanner_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryvideos',
            name='video_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
