# Generated by Django 4.2.2 on 2026-01-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0018_galleryvideos_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_requested',
            field=models.BooleanField(default=True),
        ),
    ]
